### PR TITLE
Contact Type Handling

### LINKED ISSUE #391: sbJSON to mdJSON translation fails with error "Contact type is missing"
Attempting to translate a ScienceBase JSON (sbJson) record to mdJson format fails with a "Contact type is missing" error.

It is unknown from where in the translation the error is being thrown. The `contact.contactType` schema element is not required.

## Steps to recreate:
  1. Go to https://dev-mdtranslator.mdeditor.org/demo
  2. Copy the sbJson from https://www.sciencebase.gov/catalog/item/5b747bd5e4b0f5d5787ed2ad?format=json
  3. Paste the JSON into input metadata file area
  4. Set translation options: `Reader = sbJson`, `Writer = mdJson`
  5. Select "Submit"

## Observed behavior:
Translation fails with "Contact type is missing" error.

## Expected behavior:

- A valid mdJson record should be created.
- If the error is related to setting the mdJson `contact.isOrganization` property, then `isOrganization` should be set to FALSE
- If the error is due to the inability to set a contact role, then the role code name should be set to "unknown"

### PR DESCRIPTION
**Pull request by jwaspin**
Closes #391 

**!!Confirm this satisfies the above before merging!!**

# Changes

- Fix contact type handling to set default value and log missing type message

### CODE REVIEW

File: lib/adiwg/mdtranslator/readers/sbJson/modules/module_contact.rb [hunk 1]
```diff
@@ -226,12 +226,17 @@ def self.unpack(hSbJson, aContacts, hCitation, hResponseObj)
...
+                              hContact[:contactType] = 'missing'
+                              hResponseObj[:readerExecutionMessages] << 'Contact type is missing'
+                              hResponseObj[:readerExecutionMessages] << "Contact type set to 'missing'"
+                           else
+                              hContact[:contactType] = hSbContact['type']
+                           end
+                        else
+                           hContact[:contactType] = 'missing'
                            hResponseObj[:readerExecutionMessages] << 'Contact type is missing'
-                           hResponseObj[:readerExecutionPass] = false
```
Comment (jwaspin) [inline lib/adiwg/mdtranslator/readers/sbJson/modules/module_contact.rb:233]: This was removed, not sure if that's correct

Comment (hmaier-fws) [reply lib/adiwg/mdtranslator/readers/sbJson/modules/module_contact.rb:233]: I assume this would cause the translation to fail if the type is missing. If so, then that should only happen if the translator uses the "validate=strict" option. However, the strict option is defined as "_the input must meet the maximum rule set defined by the reader schema, all fields must have values_".

But, the sbJSON is sometimes created by ScienceBase without the element. I think deleting this is OK.

**Review by hmaier-fws — APPROVED** [review]
It looks like this is what we want
